= Apache Causeway - Stuff
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

Project umbrella for the _Apache Causeway_ framework, containing stuff,
that is NOT released under the official ASF umbrella. 
____
https://causeway.apache.org[Apache Causeway] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

== Modules

* `commons` - Shared general purpose *utilities*.
* `domsupport` - Provides *Domain Support* service interfaces as expressed by the code generator (tooling-codegen). 

=== Tooling

* `codegen` - A *Java code generator* utilizing _Apache Causeway's_ programming model
* `javapoet` - Is a library for Java source file generation. We relocated the packages to `org.causewaystuff.tooling.javapoet.*` and patched it with support for Java records.

== License
_Causewaystuff_ is _Open Source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
  