= Apache Causeway - Stuff
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

Project umbrella for the _Apache Causeway_ framework, containing stuff,
that is NOT released under the official ASF umbrella. 
____
https://causeway.apache.org[Apache Causeway] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

== Modules

* `commons` - Shared general purpose *utilities*.

=== Blobstore

Blob storage API and implementations.

* `blobstore-applib` - Blob storage API.
* `blobstore-localfs` - Blob storage implementation utilizing the host's file system.
* `blobstore-testsupport` - Blob storage test templates, used by blob storage implementations.

=== Companion

Companion to the _Apache Causeway_ framework, offering supplementary types and services.

* `companion-applib` - Provides *Domain Support* service interfaces as expressed by the code generator (companion-codegen).
* `companion-codegen` - A *Java code generator* utilizing _Apache Causeway's_ programming model

=== Tooling

* `tooling-javapoet` - Is a library for Java source file generation. We relocated its packages to `org.causewaystuff.tooling.javapoet.*` 
and patched them with support for Java records.

== License
_Causewaystuff_ is _open-source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
  