= Apache Causeway - Stuff
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

Project umbrella for the _Apache Causeway_ framework, containing stuff,
that is NOT released under the official ASF umbrella. 
____
https://causeway.apache.org[Apache Causeway] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

== Modules

=== Commons

Shared general purpose utilities.

[cols="1,5a"]
|===

| commons-base
| Basic *utilities*.

| commons-compression
| Integrates *compression algorithms* like GZIP and LZMA.

|===


=== Blobstore

Blob storage API and implementations.

[cols="1,5a"]
|===

| blobstore-applib 
| Blob storage API.

| blobstore-localfs
| Blob storage implementation utilizing the host's file system.

| blobstore-testsupport 
| Blob storage test templates, used by blob storage implementations.

|===


=== Companion

Companion to the _Apache Causeway_ framework, offering supplementary types and services.

[cols="1,5a"]
|===

| companion-applib 
| Provides *Domain Support* service interfaces as expressed by the code generator (companion-codegen).

| companion-codegen
| A *Java code generator* utilizing _Apache Causeway's_ programming model

|===

=== Tooling

[cols="1,5a"]
|===

| tooling-c4modeling 
| Library for programmatic C4 Model generation.

See also https://c4model.com/


| tooling-javamodel 
| Code mining library for Java bytecode introspection.

| tooling-projectmodel 
| Code mining library for Gradle/Maven project module tree introspection.

|===


==== Relocated Libraries

[cols="1,5a"]
|===

| tooling-codeassert 
| _Code-Assert_ is a library that allows to assert that the source code of a project satisfies certain rules.

We relocated its packages to `io.github.causewaystuff.tooling.codeassert.*` 
and patched them with support for adoc files, also defining a stable JPMS module name.

See also https://github.com/nidi3/code-assert/pull/47

| tooling-javapoet 
| _Javapoet_ is a library for Java source file generation.

We relocated its packages to `io.github.causewaystuff.tooling.javapoet.*`
and patched them with support for Java records, also defining a stable JPMS module name. 

| tooling-structurizr 
| _Structurizr_ is a library for system diagram generation.

We relocated its packages to `io.github.causewaystuff.tooling.structurizr.*` 
and patched them with support for DSL parsing, also defining a stable JPMS module name.

|===

=== Tree View

Master/detail tree view for tree-like data structures.

[cols="1,5a"]
|===

| treeview-applib 
| Tree View API.

| treeview-metamodel
| Tree View integration.

|===

== License
_Causewaystuff_ is _open-source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
 