= Tooling

== Submodules

[cols="1,5a"]
|===

| tooling-c4modeling 
| Library for programmatic C4 Model generation.

See also https://c4model.com/

| tooling-cli 
| Command Line Interface for the _Causewaystuff Tooling_ ecosystem.

See documentation xref:modules/tooling/Tooling-CLI.adoc#[Tooling CLI]

| tooling-java2adoc 
| Code mining library for Java source to Asciidoc conversion.

| tooling-javamodel 
| Code mining library for Java bytecode introspection.

| tooling-projectmodel 
| Code mining library for Gradle/Maven project module tree introspection.

|===


== Relocated Libraries

[cols="1,5a"]
|===

| tooling-codeassert 
| _Code-Assert_ is a library that allows to assert that the source code of a project satisfies certain rules.

We relocated its packages to `io.github.causewaystuff.tooling.codeassert.*` 
and patched them with support for adoc files, also defining a stable JPMS module name.

See also https://github.com/nidi3/code-assert/pull/47

| tooling-javapoet 
| _Javapoet_ is a library for Java source file generation.

We relocated its packages to `io.github.causewaystuff.tooling.javapoet.*`
and patched them with support for Java records, also defining a stable JPMS module name. 

| tooling-structurizr 
| _Structurizr_ is a library for system diagram generation.

We relocated its packages to `io.github.causewaystuff.tooling.structurizr.*` 
and patched them with support for DSL parsing, also defining a stable JPMS module name.

|===